# Plugins
source ~/.config/kak/plugins/plug.kak/rc/plug.kak

plug "https://github.com/andreyorst/plug.kak" noload
plug "https://github.com/andreyorst/fzf.kak"
plug "https://github.com/alexherbo2/auto-pairs.kak"
plug "https://gitlab.com/Screwtapello/kakoune-state-save.git"
plug "https://github.com/danr/kakoune-easymotion"
plug "https://github.com/h-youhei/kakoune-surround"
plug "https://github.com/Delapouite/kakoune-buffers"
plug "https://github.com/kkga/saturn.kak"
plug "https://github.com/crizan/kak-rainbower"

colorscheme one-darker

# Plugin config
hook global WinCreate ^[^*]+$ %{
    editorconfig-load
}

# set-option global fzf_file_command 'rg'
# set-option global fzf_implementation 'sk'

hook global WinCreate .* %{
    enable-auto-pairs
}

# Enable LSP
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|typescript|c|cpp|racket) %{
    lsp-enable-window
}

hook global WinSetOption filetype=rust %{
    # Options
    hook window -group rust-inlay-hints BufWritePost .* rust-analyzer-inlay-hints
    hook -once -always window WinSetOption filetype=.* %{
        remove-hooks window rust-inlay-hints
    }
}

lsp-auto-hover-enable
set-option global lsp_hover_anchor true
set-option global lsp_auto_highlight_references true
set-option global lsp_hover_max_lines 30

set-option global auto_pairs ( ) { } [ ] '"' '"' ` `

set-option global rainbow_mode 0
hook global WinCreate .* %{
    rainbow-enable-window
}

# Config
set-option global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} (%opt{modeline_pos_percent}) {{context_info}} {{mode_info}} - %val{client}@[%val{session}]'
add-highlighter global/ show-matching
add-highlighter global/ wrap
add-highlighter global/ number-lines -relative -hlcursor

set-option global tabstop 4
set-option global scrolloff 5,5
set-option global ui_options terminal_assistant=none

hook global InsertChar \t %{
   exec -draft h@
}

hook global WinCreate .* %{
   set window autowrap_column 100
   autowrap-enable
}

hook global WinSetOption filetype=racket %{
    set window tabstop 2
    set window indentwidth 2
}

# Tab/Shift-Tab for completion
hook global WinCreate .* %{
   hook window InsertCompletionShow .* %{
       map window insert <tab> <c-n>
       map window insert <s-tab> <c-p>
   }

   hook window InsertCompletionHide .* %{
       unmap window insert <tab> <c-n>
       unmap window insert <s-tab> <c-p>
   }
}

# Mappings
map global normal <c-n> ': buffer-next<ret>'
map global normal <c-p> ': buffer-previous<ret>'
map global normal '#' ': comment-line<ret>'
map global normal <c-t> ': fzf-mode<ret>f'
map global goto d '<esc>: lsp-definition<ret>' -docstring 'definition'
map global user <space> ': wa; echo Written<ret>'
map global user y '<a-|>xclip -sel clipboard<ret> ;: echo Copied<ret>'
map global user f ': fzf-mode<ret>'
map global user i ': pick-buffers<ret>'
map global user d ': db<ret>'
map global user q ':write-all-quit<ret>'
map global insert <c-d> '<del>'
# FIXME: This messes with selections in insert mode
map global insert <c-w> '<a-;>b<a-;><a-d>'
map global easymotion b '<esc>: easy-motion-b<ret>'
map global easymotion <a-b> '<esc>: easy-motion-B<ret>'
map global normal <a-1> '<a-i>)i<ret><esc>s,<ret>lc<ret><esc>t)a<ret><esc>j;'

declare-user-mode surround
map global normal <a-3> ': enter-user-mode surround<ret>'
map global surround s ':surround<ret>' -docstring 'surround'
map global surround c ':change-surround<ret>' -docstring 'change'
map global surround d ':delete-surround<ret>' -docstring 'delete'

map global user s ': enter-user-mode easymotion<ret>'

# Source other files to keep this one clean
source ~/.config/kak/percent.kak
