[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
    # ^[ -> Esc
    { key = "[",      mods = "Control",   chars = "\u001B" },
    { key = "Insert", mods = "Shift",     action = "Paste"},
    { key = "Insert", mods = "Control",   action = "Copy"},
]

[mouse]
hide_when_typing = true

bindings = [
    { mouse = "Middle", action = "PasteSelection" },
]

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "fish"

[window]
dynamic_title = true

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[terminal]
